;;; claret-theme.el --- Claret theme  -*- lexical-binding: t; -*-
;;; SPDX-FileCopyrightText: 2025 Dohna <pub@lya.moe>
;;;
;;; SPDX-License-Identifier: GPL-3.0-or-later

(deftheme claret)

(let ((class  '((class color) (min-colors 88) (background dark)))
      (amber-50 "#fffbeb")
      (amber-100 "#fef3c7")
      (amber-200 "#fde68a")
      (amber-300 "#fcd34d")
      (amber-500 "#f59e0b")
      (amber-700 "#b45309")
      (amber-800 "#92400e")
      (amber-900 "#78350f")
      (blue-100 "#dbeafe")
      (blue-200 "#bfdbfe")
      (blue-300 "#93c5fd")
      (blue-400 "#60a5fa")
      (blue-500 "#3b82f6")
      (blue-600 "#2563eb")
      (blue-700 "#1d4ed8")
      (blue-800 "#1e40af")
      (blue-900 "#1e3a8a")
      (cyan-50 "#ecfeff")
      (cyan-100 "#cffafe")
      (cyan-200 "#a5f3fc")
      (cyan-300 "#67e8f9")
      (cyan-400 "#22d3ee")
      (cyan-500 "#06b6d4")
      (cyan-600 "#0891b2")
      (cyan-700 "#0e7490")
      (cyan-900 "#164e63")
      (cyan-950 "#083344")
      (fuchsia-100 "#fae8ff")
      (fuchsia-200 "#f5d0fe")
      (fuchsia-300 "#f0abfc")
      (fuchsia-400 "#e879f9")
      (fuchsia-500 "#d946ef")
      (fuchsia-600 "#c026d3")
      (fuchsia-700 "#a21caf")
      (fuchsia-800 "#86198f")
      (fuchsia-900 "#4a044e")
      (fuchsia-900 "#701a75")
      (fuchsia-950 "#4a044e")
      (green-50 "#f0fdf4")
      (green-100 "#dcfce7")
      (green-200 "#bbf7d0")
      (green-300 "#86efac")
      (green-400 "#4ade80")
      (green-500 "#22c55e")
      (green-600 "#16a34a")
      (green-700 "#15803d")
      (green-800 "#166534")
      (green-900 "#14532d")
      (green-950 "#052e16")
      (indigo-200 "#c7d2fe")
      (indigo-300 "#a5b4fc")
      (indigo-500 "#6366f1")
      (indigo-600 "#4f46e5")
      (indigo-800 "#3730a3")
      (indigo-900 "#312e81")
      (indigo-950 "#1e1b4b")
      (lime-50 "#f7fee7")
      (lime-100 "#ecfccb")
      (lime-200 "#d9f99d")
      (lime-300 "#bef264")
      (lime-400 "#a3e635")
      (lime-500 "#84cc16")
      (lime-600 "#65a30d")
      (lime-700 "#4d7c0f")
      (lime-800 "#3f6212")
      (lime-900 "#365314")
      (lime-950 "#1a2e05")
      (neutral-50 "#fafafa")
      (neutral-100 "#f5f5f5")
      (neutral-200 "#e5e5e5")
      (neutral-300 "#d4d4d4")
      (neutral-400 "#a3a3a3")
      (neutral-500 "#737373")
      (neutral-600 "#525252")
      (neutral-700 "#404040")
      (neutral-800 "#262626")
      (neutral-900 "#171717")
      (neutral-950 "#0a0a0a")
      (orange-100 "#ffedd5")
      (orange-200 "#fed7aa")
      (orange-300 "#fdba74")
      (orange-400 "#fb923c")
      (orange-500 "#f97316")
      (orange-600 "#ea580c")
      (orange-700 "#c2410c")
      (orange-800 "#9a3412")
      (orange-900 "#7c2d12")
      (pink-50 "#fdf2f8")
      (pink-100 "#fce7f3")
      (pink-200 "#fbcfe8")
      (pink-300 "#f9a8d4")
      (pink-500 "#ec4899")
      (pink-700 "#be185d")
      (pink-800 "#9d174d")
      (pink-900 "#831843")
      (pink-950 "#500724")
      (purple-100 "#f3e8ff")
      (purple-400 "#c084fc")
      (purple-500 "#a855f7")
      (purple-600 "#9333ea")
      (purple-700 "#7e22ce")
      (purple-800 "#6b21a8")
      (purple-950 "#3b0764")
      (red-50 "#fef2f2")
      (red-100 "#fee2e2")
      (red-200 "#fecaca")
      (red-300 "#fca5a5")
      (red-400 "#f87171")
      (red-500 "#ef4444")
      (red-600 "#dc2626")
      (red-700 "#b91c1c")
      (red-800 "#991b1b")
      (red-900 "#7f1d1d")
      (rose-50 "#fff1f2")
      (rose-100 "#ffe4e6")
      (rose-200 "#fecdd3")
      (rose-300 "#fda4af")
      (rose-400 "#fb7185")
      (rose-500 "#f43f5e")
      (rose-600 "#e11d48")
      (rose-700 "#be123c")
      (rose-800 "#9f1239")
      (rose-900 "#881337")
      (rose-950 "#4c0519")
      (sky-500 "#0ea5e9")
      (slate-400 "#94a3b8")
      (stone-100 "#f5f5f4")
      (stone-200 "#e7e5e4")
      (stone-300 "#d6d3d1")
      (stone-400 "#a8a29e")
      (stone-500 "#78716c")
      (stone-600 "#57534e")
      (stone-700 "#44403c")
      (stone-800 "#292524")
      (violet-500 "#8b5cf6")
      (violet-600 "#7c3aed")
      (yellow-50 "#fefce8")
      (yellow-100 "#fef9c3")
      (yellow-200 "#fef08a")
      (yellow-300 "#fde047")
      (yellow-400 "#facc15")
      (yellow-500 "#eab308")
      (yellow-600 "#ca8a04")
      (yellow-700 "#854d0e")
      (yellow-800 "#a16207")
      (yellow-900 "#713f12")
      (yellow-950 "#422006"))
  (custom-theme-set-faces
   `claret
   `(default ((,class (:background ,neutral-900 :foreground ,neutral-200))))

     ;;; Basic
   `(ansi-color-black ((,class (:foreground ,neutral-900))))
   `(ansi-color-blue ((,class (:foreground ,blue-900))))
   `(ansi-color-bold ((,class (:inherit bold))))
   `(ansi-color-bright-black ((,class (:foreground ,neutral-700))))
   `(ansi-color-bright-blue ((,class (:foreground ,blue-500))))
   `(ansi-color-bright-cyan ((,class (:foreground ,cyan-500))))
   `(ansi-color-bright-green ((,class (:foreground ,green-500))))
   `(ansi-color-bright-magenta ((,class (:foreground ,purple-500))))
   `(ansi-color-bright-red ((,class (:foreground ,red-500))))
   `(ansi-color-bright-white ((,class (:foreground ,neutral-50))))
   `(ansi-color-bright-yellow ((,class (:foreground ,yellow-500))))
   `(ansi-color-cyan ((,class (:foreground ,cyan-700))))
   `(ansi-color-faint ((,class ())))
   `(ansi-color-fast-blink ((,class (:box (1 . -1)))))
   `(ansi-color-green ((,class (:foreground ,green-700))))
   `(ansi-color-inverse ((,class (:inverse-video t))))
   `(ansi-color-italic ((,class (:inherit italic))))
   `(ansi-color-magenta ((,class (:foreground ,purple-700))))
   `(ansi-color-red ((,class (:foreground ,red-700))))
   `(ansi-color-slow-blink ((,class (:box (1 . -1)))))
   `(ansi-color-underline ((,class (:inherit underline))))
   `(ansi-color-white ((,class (:foreground ,neutral-100))))
   `(ansi-color-yellow ((,class (:foreground ,yellow-700))))

   `(bold ((,class (:weight bold))))
   `(button ((,class (:foreground ,indigo-500 :underline t))))
   `(cursor ((,class (:background ,neutral-400))))
   `(success ((,class (:foreground ,lime-500))))
   `(warning ((,class (:foreground ,yellow-500))))
   `(error ((,class (:foreground ,red-500))))
   `(escape-glyph ((,class (:foreground ,stone-500))))
   `(fringe ((,class ())))
   `(match ((,class :background ,amber-800 :distant-foreground ,neutral-200)))
   `(highlight ((,class (:background ,amber-900 :distant-foreground ,neutral-50))))
   `(internal-border ((,class (:background ,neutral-900))))
   `(link ((,class (:foreground ,yellow-200 :underline t))))
   `(link-visited ((,class (:foreground ,amber-200 :underline t))))
   `(region ((,class (:background ,stone-700 :distant-foreground ,neutral-300 :extend nil))))
   `(secondary-selection ((,class (:background ,indigo-900 :extend nil))))
   `(line-number ((,class (:inherit default :foreground ,neutral-600))))
   `(line-number-current-line ((,class (:inherit default :foreground ,neutral-200))))
   `(fixed-pitch ((,class ())))
   `(fixed-pitch-serif ((,class ())))
   `(variable-pitch ((,class ())))
   `(variable-pitch-text ((,class ())))
   `(buffer-menu-buffer ((,class (:inherit font-lock-constant-face))))
   `(completions-first-difference ((,class ())))
   `(completions-common-part ((,class (:background ,pink-950 :foreground ,pink-200))))

   ;;; paren
   `(blink-matching-paren-offscreen ((,class ())))
   `(show-paren-match ((,class (:background ,pink-950 :foreground ,neutral-200))))
   `(show-paren-match-expression ((,class (:background ,pink-950 :foreground ,neutral-900))))
   `(show-paren-mismatch ((,class (:background ,pink-700))))

   ;;; flymake
   `(flymake-warning ((,class (:underline (:color ,yellow-600 :style wave)))))
   `(flymake-error ((,class (:underline (:color ,red-600 :style wave)))))
   `(flymake-note ((,class (:underline (:color ,blue-600 :style wave)))))

   ;;; font-lock faces
   `(font-lock-bracket-face ((,class (:inherit font-lock-punctuation-face))))
   `(font-lock-builtin-face ((,class (:foreground ,pink-200))))
   `(font-lock-comment-delimiter-face ((,class (:inherit font-lock-punctuation-face))))
   `(font-lock-comment-face ((,class (:foreground ,neutral-500))))
   `(font-lock-constant-face ((,class (:foreground ,neutral-100))))
   `(font-lock-delimiter-face ((,class (:foreground ,neutral-600))))
   `(font-lock-doc-face ((,class (:foreground ,rose-100))))
   `(font-lock-doc-markup-face ((,class (:inherit font-lock-constant-face))))
   `(font-lock-escape-face ((,class (:foreground ,violet-500))))
   `(font-lock-function-name-face ((,class (:foreground ,rose-400))))
   `(font-lock-keyword-face ((,class (:foreground ,neutral-50))))
   `(font-lock-misc-punctuation-face ((,class (:inherit font-lock-punctuation-face))))
   `(font-lock-negation-char-face ((,class (:foreground ,orange-300))))
   `(font-lock-number-face ((,class (:foreground ,yellow-300))))
   `(font-lock-operator-face ((,class (:foreground ,neutral-500))))
   `(font-lock-property-face ((,class ())))
   `(font-lock-punctuation-face ((,class (:foreground ,neutral-600))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground ,violet-500))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground ,violet-500))))
   `(font-lock-string-face ((,class (:foreground ,rose-300))))
   `(font-lock-type-face ((,class (:foreground ,stone-300))))
   `(font-lock-variable-name-face ((,class (:foreground ,neutral-400))))
   `(font-lock-warning-face ((,class (:inherit warning))))

    ;;; eglot
   `(eglot-mode-line ((,class ())))
   `(eglot-highlight-symbol-face ((,class (:underlint t))))
   `(eglot-inlay-hint-face ((,class (:inherit font-lock-comment-face :height 0.8))))
   `(eglot-semantic-operator-face ((,class (:inherit font-lock-operator-face))))
   `(eglot-semantic-method-face ((,class (:inherit font-lock-function-call-face))))

   ;;; highlight
   `(highlight-numbers-number ((,class (:inherit font-lock-number-face))))

   ;;; hl-line
   `(hl-line ((,class (:background ,neutral-800))))

   ;;; minibuffer
   `(minibuffer-prompt ((,class ())))

   ;;; isearch
   `(lazy-highlight ((,class (:background ,fuchsia-800 :foreground ,neutral-100))))
   `(isearch ((,class (:background ,pink-800))))
   `(isearch-fail ((,class ())))
   `(isearch-group-1 ((,class (:background ,fuchsia-700))))
   `(isearch-group-2 ((,class (:background ,fuchsia-600))))

   ;;; tab bar
   `(tab-bar ((,class (:box nil))))
   `(tab-bar-tab ((,class (:inherit mode-line :box (:line-width 5 :color ,neutral-900) :underline ,neutral-700 :overline nil))))
   `(tab-bar-tab-inactive ((,class (:inherit mode-line-inactive :box (:line-width 5 :color ,neutral-900) :underline ,neutral-50 :overline nil))))

   ;;; header line
   `(header-line ((,class (:background ,neutral-700 :underline (:color ,neutral-500)))))

   ;;; mode line
   `(mode-line ((,class (:overline ,neutral-400 :box ,neutral-900 :background ,neutral-900 :foreground ,neutral-200))))
   `(mode-line-inactive ((,class (:inherit mode-line :overline ,neutral-600 :foreground ,neutral-500))))
   `(mode-line-highlight ((,class (:inherit highlight))))

   ;;; pulse
   `(pulse-highlight-start-face ((,class (:inherit region :extend t))))
   `(pulse-highlight-face ((,class (:inherit region :extend t))))

   ;;; Meow
   `(meow-beacon-indicator ((,class ())))
   `(meow-keypad-indicator ((,class ())))
   `(meow-insert-indicator ((,class ())))
   `(meow-normal-indicator ((,class ())))
   `(meow-motion-indicator ((,class ())))
   `(meow-keypad-cursor ((,class (:background ,neutral-100))))
   `(meow-normal-cursor ((,class (:background ,neutral-100))))
   `(meow-motion-cursor ((,class (:background ,neutral-100))))
   `(meow-unknown-cursor ((,class (:background ,neutral-100))))
   `(meow-beacon-cursor ((,class (:background ,indigo-200))))
   `(meow-insert-cursor ((,class (:background ,pink-500))))

   ;;; dired
   `(dired-broken-symlink ((,class (:background ,red-600))))
   `(dired-directory ((,class (:foreground ,blue-200))))
   `(dired-flagged ((,class ())))
   `(dired-header ((,class ())))
   `(dired-ignored ((,class (:strike-through t :foreground ,neutral-600))))
   `(dired-mark ((,class ())))
   `(dired-marked ((,class ())))
   `(dired-perm-write ((,class (:foreground ,yellow-800))))
   `(dired-set-id ((,class ())))
   `(dired-special ((,class ())))
   `(dired-symlink ((,class ())))
   `(dired-warning ((,class ())))

   ;;; diredfl
   `(diredfl-autofile-name ((,class ())))
   `(diredfl-compressed-file-name ((,class (:inherit diredfl-file-name))))
   `(diredfl-compressed-file-suffix ((,class (:inherit diredfl-file-suffix))))
   `(diredfl-date-time ((,class (:foreground ,neutral-500))))
   `(diredfl-deletion ((,class (:background ,red-900 :foreground ,red-300))))
   `(diredfl-deletion-file-name ((,class (:background ,red-900))))
   `(diredfl-dir-heading ((,class (:inherit font-lock-constant-face))))
   `(diredfl-dir-name ((,class (:inherit dired-directory))))
   `(diredfl-dir-priv ((,class (:inherit diredfl-dir-name))))
   `(diredfl-exec-priv ((,class (:foreground ,red-800))))
   `(diredfl-executable-tag ((,class ())))
   `(diredfl-file-name ((,class (:foreground ,neutral-200))))
   `(diredfl-file-suffix ((,class (:foreground ,neutral-500))))
   `(diredfl-flag-mark ((,class ())))
   `(diredfl-flag-mark-line ((,class (:background ,cyan-900))))
   `(diredfl-ignored-file-name ((,class (:inherit dired-ignored))))
   `(diredfl-link-priv ((,class ())))
   `(diredfl-no-priv ((,class (:foreground ,neutral-700))))
   `(diredfl-number ((,class (:foreground ,neutral-600))))
   `(diredfl-other-priv ((,class (:background ,red-800))))
   `(diredfl-rare-priv ((,class (:background ,red-800))))
   `(diredfl-read-priv ((,class (:foreground ,lime-800))))
   `(diredfl-symlink ((,class ())))
   `(diredfl-tagged-autofile-name ((,class ())))
   `(diredfl-write-priv ((,class (:inherit dired-perm-write))))

   ;;; sh-script
   `(sh-escaped-newline ((,class ())))
   `(sh-heredoc ((,class ())))
   `(sh-quoted-exec ((,class (:foreground ,neutral-400))))

   ;;; diff
   `(diff-refine-added ((,class (:background ,green-800))))
   `(diff-refine-changed ((,class (:background ,yellow-800))))
   `(diff-refine-removed ((,class (:background ,red-800))))

   ;;; diff-hl
   `(diff-hl-change ((,class (:foreground ,stone-700))))
   `(diff-hl-delete ((,class (:foreground ,red-700))))
   `(diff-hl-insert ((,class (:foreground ,green-700))))

   ;;; vertico
   `(vertico-current ((,class (:underline (:position 1) :extend nil))))

   ;;; marginalia
   `(marginalia-documentation ((,class (:inherit variable-pitch))))

   ;;; orderless
   `(orderless-match-face-0 ((,class (:inherit completions-common-part))))
   `(orderless-match-face-1 ((,class (:background ,lime-950 :foreground ,lime-200))))
   `(orderless-match-face-2 ((,class (:background ,yellow-950 :foreground ,amber-200))))
   `(orderless-match-face-3 ((,class (:background ,cyan-950 :foreground ,cyan-200))))

   ;;; citre
   `(citre-peek-ace-str-face ((,class (:background ,violet-600 :foreground ,neutral-100))))
   `(citre-peek-border-face ((,class (:height 15 :background ,rose-800 :extend t))))
   `(citre-peek-current-symbol-face ((,class (:inherit font-lock-constant-face))))
   `(citre-peek-symbol-face ((,class (:inherit default))))
   `(citre-tag-annotation-face ((,class (:inherit font-lock-keyword-face))))
   `(citre-tag-path-face ((,class (:inherit font-lock-function-name-face))))

   ;;; corfu
   `(corfu-annotations ((,class (:inherit completions-annotations))))
   `(corfu-bar ((,class (:background ,neutral-600))))
   `(corfu-border ((,class (:background ,neutral-700))))
   `(corfu-current ((,class (:background ,neutral-800))))
   `(corfu-default ((,class (:background ,neutral-950))))
   `(corfu-deprecated ((,class (:inherit shadow :strike-through t))))
   `(corfu-popupinfo ((,class (:inherit corfu-default))))

   ;;; org
   `(org-document-title ((,class (:inherit variable-pitch-text :height 1.2 :foreground ,blue-500))))
   `(org-level-1 ((,class (:inherit variable-pitch-text :height 1.35 :foreground ,neutral-50))))
   `(org-level-2 ((,class (:inherit variable-pitch-text :height 1.3 :foreground ,rose-200))))
   `(org-level-3 ((,class (:inherit variable-pitch-text :height 1.2 :foreground ,green-200))))
   `(org-level-4 ((,class (:inherit variable-pitch-text :height 1.1 :foreground ,yellow-200))))
   `(org-level-5 ((,class (:inherit variable-pitch-text :height 1.1 :foreground ,fuchsia-200))))
   `(org-level-6 ((,class (:inherit variable-pitch-text :height 1.1 :foreground ,cyan-200))))
   `(org-level-7 ((,class (:inherit variable-pitch-text :height 1.1 :foreground ,lime-200))))
   `(org-level-8 ((,class (:inherit variable-pitch-text :height 1.1 :foreground ,blue-200))))
   `(outline-1 ((,class (:foreground ,neutral-50))))
   `(outline-2 ((,class (:foreground ,rose-200))))
   `(outline-3 ((,class (:foreground ,green-200))))
   `(outline-4 ((,class (:foreground ,yellow-200))))
   `(outline-5 ((,class (:foreground ,fuchsia-200))))
   `(outline-6 ((,class (:foreground ,cyan-200))))
   `(outline-7 ((,class (:foreground ,lime-200))))
   `(outline-8 ((,class (:foreground ,blue-200))))
   `(org-verbatim ((,class (:inherit (fixed-pitch font-lock-keyword-face)))))
   `(org-table ((,class (:inherit fixed-pitch))))
   `(org-code ((,class (:inherit fixed-pitch))))
   `(org-latex-and-related ((,class (:inherit fixed-pitch))))
   `(org-checkbox ((,class (:inherit fixed-pitch))))
   `(org-block ((,class (:inherit fixed-pitch))))
   `(org-special-keyword ((,class (:inherit fixed-pitch))))
   `(org-meta-line ((,class (:inherit fixed-pitch))))
   `(org-document-info-keyword ((,class (:inherit org-meta-line))))
   `(org-hide ((,class (:background ,neutral-900))))
   `(org-indent ((,class (:inherit (fixed-pitch org-hide)))))

   ;;; rst
   `(rst-level-1 ((,class (:foreground ,neutral-100))))
   `(rst-level-2 ((,class (:foreground ,rose-200))))
   `(rst-level-3 ((,class (:foreground ,green-200))))
   `(rst-level-4 ((,class (:foreground ,yellow-200))))
   `(rst-level-5 ((,class (:foreground ,fuchsia-200))))
   `(rst-level-6 ((,class (:foreground ,cyan-200))))

   ;;; ace-window
   `(aw-leading-char-face ((,class (:inherit font-lock-keyword-face :height 3.0))))
   `(aw-minibuffer-leading-char-face ((,class (:inherit font-lock-keyword-face :height 1.0))))

   ;;; magit
   `(magit-diff-hunk-heading ((,class (:background ,neutral-900))))
   `(magit-diff-hunk-heading-highlight ((,class (:background ,neutral-800))))
   `(magit-diff-added ((,class (:background ,green-800 :foreground, green-200))))
   `(magit-diff-added-highlight ((,class (:background ,green-800 :foreground, green-100))))
   `(magit-diff-removed ((,class (:background ,red-700 :foreground, red-200))))
   `(magit-diff-removed-highlight ((,class (:background ,red-700 :foreground, red-100))))
   `(magit-section-highlight ((,class (:background ,neutral-800))))
   `(magit-diff-context-highlight ((,class (:inherit magit-section-highlight))))
   `(magit-diff-lines-heading ((,class (:background ,orange-700))))

   ;;; eldoc-box
   `(eldoc-box-border ((,class (:background ,neutral-700))))

   ;;; whitespace
   `(whitespace-big-indent ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-empty ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-hspace ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-indentation ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-line ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-missing-newline-at-eof ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-newline ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-space ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-space-after-tab ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-space-before-tab ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-tab ((,class (:inherit font-lock-punctuation-face))))
   `(whitespace-trailing ((,class (:inherit font-lock-punctuation-face))))

   ;;; wgrep
   `(wgrep-face ((,class ())))
   `(wgrep-delete-face ((,class ())))
   `(wgrep-file-face ((,class ())))
   `(wgrep-reject-face ((,class ())))
   `(wgrep-done-face ((,class ())))

   ;;; erc
   `(erc-nick-default-face ((,class (:inherit font-lock-function-name-face))))
   `(erc-notice-face ((,class (:inherit font-lock-comment-face))))
   ))

;;;###autoload
(when (and (boundp 'custom-theme-load-path) load-file-name)
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'claret)
